# Generated by Django 5.2.6 on 2025-09-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.IntegerField()),
                ('clase_de_aviso', models.CharField(max_length=10)),
                ('orden', models.IntegerField()),
                ('ubicacion_tecnica', models.CharField(max_length=100)),
                ('denominacion_de_objeto_tecnico', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('pto_tbjo_responsable', models.CharField(max_length=20)),
                ('inicio_deseado', models.DateField()),
                ('fin_deseado', models.DateField()),
                ('sociedad', models.CharField(max_length=10)),
                ('status_de_usuario', models.CharField(max_length=20)),
                ('orden_1', models.IntegerField()),
                ('clase_de_orden', models.CharField(max_length=10)),
                ('revision', models.CharField(max_length=10)),
                ('ubicacion_tecnica_1', models.CharField(max_length=100)),
                ('texto_breve', models.CharField(max_length=100)),
                ('pto_tbjo_responsable_1', models.CharField(max_length=20)),
                ('fecha_de_inicio_extrema', models.DateField()),
                ('fecha_fin_extrema', models.DateField()),
                ('tota_general_plan', models.FloatField()),
                ('total_general_real', models.FloatField()),
                ('indicador_ABC', models.CharField(max_length=10)),
                ('status_del_sistema', models.CharField(max_length=100)),
                ('sociedad_CO', models.CharField(max_length=10)),
                ('planes_trab', models.CharField(max_length=10)),
                ('clase_consignacion', models.CharField(max_length=10)),
                ('estado', models.IntegerField()),
                ('ub_tecnica_busqueda', models.CharField(max_length=100)),
                ('denominacion_de_la_revision', models.CharField(max_length=100)),
                ('fecha_inic_revision', models.DateField()),
                ('hora_inic_revision', models.FloatField()),
                ('fecha_fin_revision', models.DateField()),
                ('hora_fin_revision', models.FloatField()),
                ('desc_jefe_trab', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=10)),
                ('instalacion', models.CharField(max_length=10)),
            ],
        ),
    ]
