# Generated by Django 5.2.6 on 2025-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrossap',
            name='aviso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
