# Generated by Django 5.2.6 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0002_alter_registrossap_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrossap',
            name='clase_de_aviso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
