# Generated by Django 5.2.6 on 2025-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0003_alter_registrossap_clase_de_aviso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrossap',
            name='clase_consignacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='clase_de_orden',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='denominacion_de_la_revision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='denominacion_de_objeto_tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='desc_jefe_trab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='fecha_de_inicio_extrema',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='fecha_fin_extrema',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='fecha_fin_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='fecha_inic_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='fin_deseado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='hora_fin_revision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='hora_inic_revision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='indicador_ABC',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='inicio_deseado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='instalacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='orden_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='planes_trab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='pto_tbjo_responsable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='pto_tbjo_responsable_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='sociedad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='sociedad_CO',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='st',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='status_de_usuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='status_del_sistema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='texto_breve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='tota_general_plan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='total_general_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='ub_tecnica_busqueda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='ubicacion_tecnica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrossap',
            name='ubicacion_tecnica_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
