# Generated by Django 5.2.6 on 2025-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sap', '0004_alter_registrossap_clase_consignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrossap',
            name='status_de_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
